[build]
packages = [
    "pyroll"
]

[version]
path = "pyroll/ring_model_thermal/__init__.py"

[envs.default]
path = ".venv"
dependencies = [
    "pytest ~= 7.0",
    "pyroll-report ~= 2.0",
]

[envs.docs]
path = ""
dependencies = [
    "pygments ~= 2.0",
    "pytask ~= 0.2.0",
    "pytask_latex ~= 0.2.0",
    "jinja2 ~= 3.0",
    "tomli ~= 2.0"
]

[envs.docs.scripts]
build = "python -m pytask"

[envs.test]
path = ""

[envs.test.scripts]
all = "pytest"

[[envs.test.matrix]]
python = ["3.9", "3.10", "3.11"]