[[symbol]]
name = "Time"
code = 't'
descr = "Time"
sort = "t"

[[symbol]]
name = "Radius"
code = 'r'
descr = "Radius coordinate of a ring's center line"

[[symbol]]
name = "RadiusBoundary"
code = 'R'
descr = "Radius coordinate of a ring's boundary line"

[[symbol]]
name = "MassFlow"
code = '\dot{m}'
descr = "Mass flow in x-direction"

[[symbol]]
name = "Density"
code = '\varrho'
descr = "Density"

[[symbol]]
name = "SpecificHeatCapacity"
code = 'c_\mathrm{p}'
descr = "Specific Heat Capacity"

[[symbol]]
name = "X"
code = 'x'
descr = "X Coordinate"

[[symbol]]
name = "XWidth"
code = '\Delta x'
descr = "Discretization width in x"

[[symbol]]
name = "TimeWidth"
code = '\Delta t'
descr = "Discretization width in time"

[[symbol]]
name = "Temperature"
code = 'T'
descr = "Absolute temperature"

[[symbol]]
name = "SurfaceTemperature"
code = 'T_\mathrm{S}'
descr = "Absolute surface temperature"

[[symbol]]
name = "EnvironmentTemperature"
code = 'T_\infty'
descr = "Environemnt temperature"

[[symbol]]
name = "RadiusWidth"
code = '\Delta r'
descr = "Discretization width in radius"

[[symbol]]
name = "ThermalConductivity"
code = '\lambda'
descr = "Thermal conductivity"

[[symbol]]
name = "HeatFlow"
code = '\dot{q}'
descr = "Heat flow"

[[symbol]]
name = "HeatSource"
code = '\dot{q}_\mathrm{S}'
descr = "Heat source (generation)"

[[symbol]]
name = "HeatTransferCoefficient"
code = '\alpha'
descr = "Heat transfer coefficient"

[[symbol]]
name = "RadiationCoefficient"
code = '\epsilon_0'
descr = "Radiation coeffient of black radiator"

[[symbol]]
name = "RelativeRadiationCoefficient"
code = '\epsilon_\mathrm{r}'
descr = "Relative radiation coeffient"

[[symbol]]
name = "RingIndex"
code = 'i'
descr = "Index of the ring"

[[symbol]]
name = "RingBoundaryIndex"
code = 'j'
descr = "Index of the ring boundary"

[[symbol]]
name = "DiskIndex"
code = 'k'
descr = "Index of the disk element"

[[symbol]]
name = "RingIndexMax"
code = '\hat{\imath}'
descr = "Maximum index of the ring"

[[symbol]]
name = "RingCount"
code = 'n'
descr = "Count of rings"

[[symbol]]
name = "RingBoundaryIndexMax"
code = '\hat{\jmath}'
descr = "Maximum index of the ring boundary"

[[symbol]]
name = "TemperatureIncrement"
code = '\Delta T'
descr = "Increment of temperature"

[[symbol]]
name = "Volume"
code = 'V'
descr = "Volume of the disk element rep. layer"

[[symbol]]
name = "VolumeFlow"
code = '\dot{V}'
descr = "Volume flow"

[[symbol]]
name = "CrossSection"
code = 'A'
descr = "Cross-section area"

[[symbol]]
name = "Interface"
code = 'I'
descr = "Interface length"


[[symbol]]
name = "FormingEfficiency"
code = '\eta_\varphi'
descr = "Efficiency of deformation"

[[symbol]]
name = "HeatSourceEfficiency"
code = '\eta_\mathrm{S}'
descr = "Efficiency of heat source by deformation"

[[symbol]]
name = "FlowStress"
code = 'k_\mathrm{f}'
descr = "Flow stress"

[[symbol]]
name = "Strain"
code = '\varphi'
descr = "Equivalent strain"

[[symbol]]
name = "StrainRate"
code = '\dot{\varphi}'
descr = "Equivalent strain rate"


[[symbol]]
name = "Velocity"
code = 'v'
descr = "Velocity of material flow"
